// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuK8n4vUW5l89BK7dSiIDPWJd8VjBzWfk',
    appId: '1:554804767970:web:b8a65722672ce2d34bc2bb',
    messagingSenderId: '554804767970',
    projectId: 'alerte-ocean',
    authDomain: 'alerte-ocean.firebaseapp.com',
    storageBucket: 'alerte-ocean.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZHoJQ-jSWySbcyZepzhMIBE9iJbFZW4',
    appId: '1:554804767970:android:ef75fd1ce01454ac4bc2bb',
    messagingSenderId: '554804767970',
    projectId: 'alerte-ocean',
    storageBucket: 'alerte-ocean.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-muaZs2KXidWlhDPlNzKKxR_AdEAZeA',
    appId: '1:554804767970:ios:4dcbbb1b54c0eadd4bc2bb',
    messagingSenderId: '554804767970',
    projectId: 'alerte-ocean',
    storageBucket: 'alerte-ocean.appspot.com',
    iosBundleId: 'com.alerteocean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-muaZs2KXidWlhDPlNzKKxR_AdEAZeA',
    appId: '1:554804767970:ios:4dcbbb1b54c0eadd4bc2bb',
    messagingSenderId: '554804767970',
    projectId: 'alerte-ocean',
    storageBucket: 'alerte-ocean.appspot.com',
    iosBundleId: 'com.alerteocean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuK8n4vUW5l89BK7dSiIDPWJd8VjBzWfk',
    appId: '1:554804767970:web:c9d9a3a5d87bfcef4bc2bb',
    messagingSenderId: '554804767970',
    projectId: 'alerte-ocean',
    authDomain: 'alerte-ocean.firebaseapp.com',
    storageBucket: 'alerte-ocean.appspot.com',
  );
}
